FROM node:dubnium-alpine AS project-zeus-builder
ADD package.json /project-zeus/
ADD package-lock.json /project-zeus/
WORKDIR /project-zeus/
RUN npm run setup

FROM project-zeus-builder AS project-zeus
WORKDIR /project-zeus/
ENV NODE_ENV="production"
ADD . /project-zeus/
RUN npm run build
EXPOSE 3001/tcp
CMD [ "npm", "run", "start:heroku" ]
